name: Test My Node application

on:
  push:
    branch: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      # How to use MySQL
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Adding MySQL Client for Initializing DB
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
      - name: Initializing DB
        run: mysql --port ${{ job.services.mysql.ports[3306] }} -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS test;'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: yarn
      - name: Running Tests
        env:
          DB_PASSWORD: root
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_HOST: localhost
          DB_USERNAME: root
          DB_NAME: test
        run: npm test
